[05/Jun/2013 16:49:27] ERROR [django.request:215] Internal Server Error: /neighborhood/seattle/date/05302011/
Traceback (most recent call last):
  File "/Users/lindsayrgwatt/.virtualenvs/neighborhood/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/lindsayrgwatt/apps/neighborhood_on_dotcloud/neighborhood/hoods/views.py", line 141, in detail
    weekend = is_weekend(validated_date[1])
  File "/Users/lindsayrgwatt/apps/neighborhood_on_dotcloud/neighborhood/hoods/views.py", line 70, in is_weekend
    if date.weekday() < 5:
AttributeError: 'NoneType' object has no attribute 'weekday'
[05/Jun/2013 20:01:55] ERROR [django.request:215] Internal Server Error: /neighborhood/seattle/date/05302011/
Traceback (most recent call last):
  File "/Users/lindsayrgwatt/.virtualenvs/neighborhood/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/lindsayrgwatt/apps/neighborhood_on_dotcloud/neighborhood/hoods/views.py", line 141, in detail
    weekend = is_weekend(validated_date[1])
  File "/Users/lindsayrgwatt/apps/neighborhood_on_dotcloud/neighborhood/hoods/views.py", line 70, in is_weekend
    if date.weekday() < 5:
AttributeError: 'NoneType' object has no attribute 'weekday'
[05/Jun/2013 20:06:12] ERROR [django.request:215] Internal Server Error: /neighborhood/seattle/date/04062013/
Traceback (most recent call last):
  File "/Users/lindsayrgwatt/.virtualenvs/neighborhood/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/lindsayrgwatt/apps/neighborhood_on_dotcloud/neighborhood/hoods/views.py", line 186, in detail
    for key, value in context:
ValueError: too many values to unpack
[05/Jun/2013 20:06:26] ERROR [django.request:215] Internal Server Error: /neighborhood/seattle/date/04062013/
Traceback (most recent call last):
  File "/Users/lindsayrgwatt/.virtualenvs/neighborhood/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/Users/lindsayrgwatt/apps/neighborhood_on_dotcloud/neighborhood/hoods/views.py", line 186, in detail
    for key, value in context.items:
TypeError: 'builtin_function_or_method' object is not iterable
[05/Jun/2013 20:46:16] WARNING [django.request:142] Not Found: /favicon.ico
[06/Jun/2013 09:41:06] WARNING [django.request:142] Not Found: /favicon.ico
[06/Jun/2013 09:41:06] WARNING [django.request:142] Not Found: /favicon.ico
